# Generated by Django 2.2.1 on 2019-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideuser',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideuser',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
