# Generated by Django 2.2.1 on 2019-06-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_remove_ideuser_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideuser',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
